### ISSUE TITLE
reconnect if redis server is miss

### ISSUE THREAD

**Issue by micron10** [dpdk-vbng-cp/accel-ppp#19]
Hi all
in test lab i find when redis server is miss redis client not try to reconnect after customer connect : 

[2021-10-29 15:51:30.596] ap_redis: redisConnect failed: (No route to host)

maybe it's good to have an option to set to try X time through X sec.

if it fails then make a mistake.

Now when accel run and redis run after accel  ( when customer connect not send info to redis.)

Martin

**Comment by akoepsel** [comment]
Hi Martin,

issue has been solved with merge request #23 . Parameter _timeout_ uses a default value of 8 seconds. You may adjust it in the configuration file in section _redis_ to suit your needs.

regards,
Andreas

**Comment by micron10** [comment]
> Hi Martin,
> 
> issue has been solved with merge request #23 . Parameter _timeout_ uses a default value of 8 seconds. You may adjust it in the configuration file in section _redis_ to suit your needs.
> 
> regards, Andreas

Thanks for fast work ! 
I will test in lab if have any problem will write you.

Martin

**Comment by micron10** [comment]
Hi @akoepsel 

Make test compile and try to connect user ,
first time with work redis server all look fine.
after that i stop redis server and reconnect user and in accel log start message : 
[2021-12-04 12:02:44.175] ap_redis: redisConnect failed: (Connection refused)
[2021-12-04 12:02:45.176] ap_redis: redisConnect failed: (Connection refused)
[2021-12-04 12:02:47.176] ap_redis: redisConnect failed: (Connection refused)


and after start redis server and try to connect user receive message : 
[2021-12-04 12:03:40.840] eth1: 169c26540235db04: recv [RADIUS(1) Access-Accept id=1 <Framed-Pool "Dynamic Private Pool"> <Mikrotik-Address-List "Users100M"> <Acct-Interim-Interval 900> <Mikrotik-Rate-Limit "102400k/102400k 112640k/112640k"> <Class 0x6375693d61736b64697075322c73753d32343134362c736b3d32697431696a6c3978786c652c626b69643d31383031363033312c626b7269643d332c6d763d3533353336363732333732322c6d743d3630353637342c676d743d3630343830302c73703d312c73723d2c61633d312c75693d32343134362c6363693d302c63633d2c61733d312c636f3d2c64623d3130323430302c75623d3130323430302c63626b69643d3138303136303332> <Reply-Message "Welcome">]

and not other message,

if redis server miss need user will connect but in accel only will see redis miss and user will establish connection.

and after timeout is finish need to set may be try to reconnect to redis server after server is back online /
now need to restart accel to start connection to redis server.


i apply patch from last commit see and set in accel-ppp.conf - redis section > timeout 8 : 

--- accel-ppp-master/accel-pppd/redis/redis.c.orig	2021-12-04 09:35:39.414284439 +0000
+++ accel-ppp-master/accel-pppd/redis/redis.c	2021-12-04 09:34:17.203704674 +0000
@@ -5,6 +5,7 @@
 #include <fcntl.h>
 #include <unistd.h>
 #include <limits.h>
+#include <math.h>
 #include <aio.h>
 #include <signal.h>
 #include <sys/stat.h>
@@ -33,7 +34,9 @@ extern char** environ;
 #define DEFAULT_NAS_ID        "accel-ppp"
 #define DEFAULT_REDIS_HOST    "localhost"
 #define DEFAULT_REDIS_PORT     6379
+#define DEFAULT_REDIS_TIMEOUT  8
 #define DEFAULT_REDIS_PUBCHAN "accel-ppp"
+#define DEFAULT_MAX_ROUNDS     4

 enum ap_redis_events_t {
 	REDIS_EV_SES_STARTING         = 0x00000001,
@@ -116,6 +119,8 @@ struct ap_redis_t {
 	char* host;
 	/* redis port */
 	uint16_t port;
+	/* redis timeout */
+	struct timeval timeout;
 	/* redis channel (publish) */
 	char* pubchan;

@@ -135,14 +140,15 @@ static struct ap_redis_t *ap_redis;
 static mempool_t redis_pool;


-static void ap_redis_dequeue(struct ap_redis_t* ap_redis, redisContext* ctx)
+static void ap_redis_dequeue(struct ap_redis_t* ap_redis, redisContext** ctx)
 {
+	redisReply *reply = NULL;
+
 	spin_lock(&ap_redis->msg_queue_lock);

 	while (!list_empty(&ap_redis->msg_queue)) {

 		struct ap_redis_msg_t* msg = list_first_entry(&(ap_redis->msg_queue), typeof(*msg), entry);
-		list_del(&msg->entry);

 		json_object* jobj = json_object_new_object();
 		json_object* jstring;
@@ -234,13 +240,71 @@ static void ap_redis_dequeue(struct ap_r
 		if (msg->subscriber_tags)
 			json_object_object_add(jobj, "subscriber_tags", json_object_new_int(msg->subscriber_tags));

-		// TODO: send msg to redis instance
-		redisReply* reply;
-		reply = redisCommand(ctx, "PUBLISH %s %s", ap_redis->pubchan, json_object_to_json_string(jobj));
-
-		if (reply) {
-			// TODO
-		}
+		/* sent message to redis */
+		unsigned int msg_sent = 0;
+		while (!msg_sent) {
+
+                        /* establish connection to redis server */
+        		if ((*ctx) == NULL) {
+		                unsigned int n_rounds = DEFAULT_MAX_ROUNDS;
+	     	                unsigned int backoff = 1;
+				while (n_rounds > 0) {
+                                        *ctx = redisConnectWithTimeout(ap_redis->host, ap_redis->port, ap_redis->timeout);
+                                        if ( ((*ctx) == NULL) || ((*ctx)->err) ) {
+                                                if (*ctx) {
+                                                        log_error("ap_redis: redisConnect failed: (%s)\n", (*ctx)->errstr);
+                		                } else {
+                			                log_error("ap_redis: failed to allocate redis context\n");
+                		                }
+        					/* sleep backoff seconds */
+                                                sleep(backoff);
+        					/* increase backoff */
+        				        backoff = (unsigned int)(pow(2, (DEFAULT_MAX_ROUNDS - n_rounds)));
+        					/* decrement n_rounds by one */
+        					n_rounds--;
+						/* return after DEFAULT_MAX_ROUNDS */
+                		                if (!n_rounds) {
+                                                        if (*ctx) {
+                                                                redisFree(*ctx);
+                                                                *ctx = NULL;
+                                                        }
+
+		                                        /* delete json object */
+                 		                        json_object_put(jobj);
+						        return;
+						}
+                	                } else {
+                                                log_info2("ap_redis: redisConnect succeeded\n");
+                                                /* redis connection established successfully */
+                                                break;
+                                        }
+        	                }
+        		}
+
+    		        /* send msg to redis instance */
+		        reply = redisCommand(*ctx, "PUBLISH %s %s", ap_redis->pubchan, json_object_to_json_string(jobj));
+        		if (reply == NULL) {
+                                log_error("ap_redis: redisCommand failed: (%s)\n", (*ctx)->errstr);
+        			switch ((*ctx)->err) {
+        			case REDIS_ERR_IO:
+        			case REDIS_ERR_EOF:
+        			case REDIS_ERR_PROTOCOL:
+        			case REDIS_ERR_OTHER:
+        			default: {
+                                        redisFree(*ctx);
+        				*ctx = NULL;
+
+		                        /* delete json object */
+                 		        json_object_put(jobj);
+        		        } return;
+        			}
+        		} else {
+			        msg_sent = 1;
+                        }
+                }
+
+		/* transmission successful: pop message from internal queue */
+		list_del(&msg->entry);

 		/* delete json object */
 		json_object_put(jobj);
@@ -282,17 +346,8 @@ static void* ap_redis_thread(void* arg)
 	struct ap_redis_t* ap_redis = (struct ap_redis_t*)arg;
 	ap_redis->thread_exit_code = -1;

-	/* establish connection to redis server */
-	redisContext *ctx;
-	ctx = redisConnect(ap_redis->host, ap_redis->port);
-	if ((ctx == NULL) || (ctx->err)) {
-		if (ctx) {
-			log_error("ap_redis: redisConnect failed: (%s)\n", ctx->errstr);
-		} else {
-			log_error("ap_redis: failed to allocate redis context\n");
-		}
-		return &(ap_redis->thread_exit_code);
-	}
+	/* redis connection context */
+	redisContext *ctx = NULL;

 	/* create epoll device */
 	int epfd;
@@ -339,7 +394,7 @@ static void* ap_redis_thread(void* arg)

 		for (unsigned int i = 0; i < 32; i++) {
 			if (epev[i].data.fd == ap_redis->evfd) {
-				ap_redis_dequeue(ap_redis, ctx);
+				ap_redis_dequeue(ap_redis, &ctx);
 			}
 		}
 	}
@@ -350,7 +405,10 @@ static void* ap_redis_thread(void* arg)
 	close(epfd);

 	/* release redis context */
-	redisFree(ctx);
+        if (ctx) {
+   	        redisFree(ctx);
+                ctx = NULL;
+        }

 	return &(ap_redis->thread_exit_code);
 }
@@ -394,10 +452,18 @@ static int ap_redis_open(struct ap_redis
 		ap_redis->host = _strdup(opt);
 	else
 		ap_redis->host = _strdup(DEFAULT_REDIS_HOST);
+
 	if (((opt = conf_get_opt("redis", "port")) != NULL))
 		ap_redis->port = strtol(opt, NULL, 0);
 	else
 		ap_redis->port = DEFAULT_REDIS_PORT;
+
+        memset(&(ap_redis->timeout), 0, sizeof(ap_redis->timeout));
+	if (((opt = conf_get_opt("redis", "timeout")) != NULL))
+		ap_redis->timeout.tv_sec = strtol(opt, NULL, 0);
+	else
+		ap_redis->timeout.tv_sec = DEFAULT_REDIS_TIMEOUT;
+
 	if (((opt = conf_get_opt("redis", "pubchan")) != NULL))
 		ap_redis->pubchan = _strdup(opt);
 	else
--- accel-ppp-master/accel-pppd/redis/CMakeLists.txt.orig2	2021-12-04 09:29:44.908409125 +0000
+++ accel-ppp-master/accel-pppd/redis/CMakeLists.txt	2021-12-04 09:34:17.399701288 +0000
@@ -9,7 +9,7 @@ IF(REDIS)
 	PKG_CHECK_MODULES(JSON_C REQUIRED json-c)

         ADD_LIBRARY(redis SHARED redis.c)
-	TARGET_LINK_LIBRARIES(redis rt pthread ${HIREDIS_LIBRARIES} ${JSON_C_LIBRARIES})
+	TARGET_LINK_LIBRARIES(redis rt pthread m ${HIREDIS_LIBRARIES} ${JSON_C_LIBRARIES})
 	TARGET_COMPILE_OPTIONS(redis PUBLIC ${HIREDIS_CFLAGS} ${JSON_C_CFLAGS})
         INSTALL(TARGETS redis
                 LIBRARY DESTINATION lib${LIB_SUFFIX}/accel-ppp


if you need to test i send me changes and will recompile here in lab and test .

Best Regards,
Martin

**Comment by akoepsel** [comment]
Hi Martin,

there is indeed a problem related to not properly releasing the spinlock when leaving function ap_redis_dequeue().
Fixed that bug in commit e7be1866ce76efe3f4bf00c524e4e6caadafecb7. I hope, this fixes any issues related to redis connection (re-)establishment. 

best regards,
Andreas

**Comment by micron10** [comment]
Hi Andreas,

Yes now work perfect thanks for this fix.

[2021-12-05 11:13:53.290] ap_redis: redisConnect failed: (Connection refused)
[2021-12-05 11:13:54.291] ap_redis: redisConnect failed: (Connection refused)
[2021-12-05 11:13:55.291] ap_redis: redisConnect failed: (Connection refused)
[2021-12-05 11:13:57.291] ap_redis: redisConnect failed: (Connection refused)
[2021-12-05 11:14:02.292] ap_redis: redisConnect failed: (Connection refused)
[2021-12-05 11:14:03.292] ap_redis: redisConnect failed: (Connection refused)
[2021-12-05 11:14:04.293] ap_redis: redisConnect failed: (Connection refused)
[2021-12-05 11:14:06.293] ap_redis: redisConnect failed: (Connection refused)
[2021-12-05 11:14:11.293] ap_redis: redisConnect failed: (Connection refused)
[2021-12-05 11:14:12.294] ap_redis: redisConnect failed: (Connection refused)
[2021-12-05 11:14:13.294] ap_redis: redisConnect failed: (Connection refused)
[2021-12-05 11:14:15.294] ap_redis: redisConnect failed: (Connection refused)
[2021-12-05 11:14:20.295] ap_redis: redisConnect failed: (Connection refused)
[[2021-12-05 11:14:21.295] ap_redis: redisConnect failed: (Connection refused)
[2021-12-05 11:14:22.296] ap_redis: redisConnect failed: (Connection refused)
[2021-12-05 11:14:24.296] ap_redis: redisConnect succeeded
