### ISSUE TITLE
Service-name tag in session-acct-start

### ISSUE THREAD

**Issue by micron10** [dpdk-vbng-cp/accel-ppp#27]
Hi team

is there options to get service-name with which the user is hooked. 

[2021-12-21 13:52:22.691] eth1: recv [PPPoE PADI 1e:45:a7:fe:40:06 => ff:ff:ff:ff:ff:ff sid=0000 **<Service-Name test>** <Host-Uniq 0f000000000000001d000000>]
[2021-12-21 13:52:22.691] eth1: send [PPPoE PADO 8e:f7:3e:82:72:17 => 1e:45:a7:fe:40:06 sid=0000 <AC-Name TESTLAB> <Service-Name test> <AC-Cookie b0475a162fd52204d9fe3d935939d62b124232f738406a89> <Host-Uniq 0f000000000000001d000000>]
[2021-12-21 13:52:22.692] eth1: recv [PPPoE PADR 1e:45:a7:fe:40:06 => 8e:f7:3e:82:72:17 sid=0000 <Service-Name test> <Host-Uniq 0f000000000000001e000000> <AC-Cookie b0475a162fd52204d9fe3d935939d62b124232f738406a89>]
[2021-12-21 13:52:22.692] eth1: send [PPPoE PADS 8e:f7:3e:82:72:17 => 1e:45:a7:fe:40:06 sid=0001 <AC-Name TESTLAB> <Service-Name test> <Host-Uniq 0f000000000000001e000000>]

3) "{ \"event\": \"session-acct-start\", \"ctrl_type\": \"pppoe\", \"channel_name\": \"1e:45:a7:fe:40:06\", \"session_id\": \"417bd71512668bd7\", \"called_station_id\": \"8e:f7:3e:82:72:17\", \"calling_station_id\": \"1e:45:a7:fe:40:06\", \"name\": \"pppoe\", \"username\": \"testuser\", \"ip_addr\": \"10.10.10.1\", \"pppoe_sessionid\": 64, \"ppp_name\": \"ppp0\", \"ctrl_ifname\": \"eth1\", \"nas_identifier\": \"testlab-01\", \"qos_val\": \"102400k\\/102400k 112640k\\/112640k\",  \"service_name\": \"test\"}"

Best Regards,
Martin

**Comment by akoepsel** [comment]
Hi Martin,

added support for service-name tag to plugins redis and sss in commit f13d1bb33355c22f2ccc70d12bb4126223b810e9.
Please give it a try.

regards,
Andreas

**Comment by micron10** [comment]
Hi @akoepsel 

apply 
add more code to show in show sessions.

But i think with this patch breaks the option to log in without service-name.

In normal case all user have service-name , but have device that not send service name ,
and in accel is allow user to login with list of service-name or with empty.

May be need to stay only check for len of service name .
if receive zero size to accept same or ?

In log : 

[2022-06-22 19:17:13.926] pppoe: Service-Name tag handling: tag length is 0
[2022-06-22 19:17:18.938] pppoe: Service-Name tag handling: tag length is 0
[2022-06-22 19:17:23.939] pppoe: Service-Name tag handling: tag length is 0
[2022-06-22 19:17:28.945] pppoe: Service-Name tag handling: tag length is 0


i apply and changes from T37

**Comment by micron10** [comment]
ok sorry fix

add this in line  1099: 

  case TAG_SERVICE_NAME:
                                if (tag->tag_len == 0 && conf_accept_null_sn) {
                                        service_match = 1;
                                        break;
                                }

I not use Dimka patch for empty service name .
i use one more advanced patch for empty service-name write before 1-2 year.
with this patch all old d-link or other router before 8-10 year connect without problem.

next i will make test in real server

**Comment by micron10** [comment]
but its same bug with Dimka and this patch
when user connect with empty service name : 

 ifname | uplinkif | servicename | username |    calling-sid    |    ip    |  rate-limit   | type  | comp | state  |  uptime
--------+----------+-------------+----------+-------------------+----------+---------------+-------+------+--------+----------
 ppp0   | eth1     | (null)      | test1 | 9a:ee:e3:61:f5:18 | 10.0.0.1 | 102400/102400 | pppoe |      | active | 00:00:03

but after connect with service name : 

ifname | uplinkif | servicename | username |    calling-sid    |    ip    |  rate-limit   | type  | comp | state  |  uptime
--------+----------+-------------+----------+-------------------+----------+---------------+-------+------+--------+----------
 ppp0   | eth1     | testservice     | test1 | 9a:ee:e3:61:f5:18 | 10.0.0.2 | 102400/102400 | pppoe |      | active | 00:00:02


but if user try to connect with wrong service name "testservice1" and not succes, and try with properly service name "testservice"

 ifname | uplinkif | servicename | username |    calling-sid    |    ip    |  rate-limit   | type  | comp | state  |  uptime
--------+----------+-------------+----------+-------------------+----------+---------------+-------+------+--------+----------
 ppp0   | eth1     | testservice1    | test1 | 9a:ee:e3:61:f5:18 | 10.0.0.4 | 102400/102400 | pppoe |      | active | 00:00:02


stay service name with try with wrong name .
not delete this service name
same check in redis-cli: 


3) "{ \"event\": \"session-acct-start\", \"ctrl_type\": \"pppoe\", \"channel_name\": \"9a:ee:e3:61:f5:18\", \"session_id\": \"15a14cc01cbf786c\", \"called_station_id\": \"6e:3a:11:37:75:e1\", \"calling_station_id\": \"9a:ee:e3:61:f5:18\", \"name\": \"pppoe\", \"username\": \"test1\", \"ip_addr\": \"10.0.0.5\", \"pppoe_sessionid\": 256, \"ppp_name\": \"ppp0\", \"ctrl_ifname\": \"eth1\", \"nas_identifier\": \"testbng\", \"qos_val\": \"102400k\\/102400k 112640k\\/112640k\", \"l4_val\": \"Dynamic Private Pool\", \"service_name\": \"testservice1\" }"

**Comment by micron10** [comment]
may be need to change logic 

and move check for empty service name in your code 
end if user login with empty service name  to write : empty or other.
and add in db if user is try with broken service name to erace this from db.

what do you think

and check this is patch witch i use for empty service name : 

[accelppp-null-sn.txt](https://github.com/dpdk-vbng-cp/accel-ppp/files/8961235/accelppp-null-sn.txt)

rename fail from .patch to .txt github not like .patch :)

**Comment by micron10** [comment]
@akoepsel  do you have time to see this

**Comment by micron10** [comment]
Hey @akoepsel 
Do you have time to see this

**Comment by micron10** [comment]
fix
