### ISSUE TITLE
Two more bug found 

### ISSUE THREAD

**Issue by micron10** [dpdk-vbng-cp/accel-ppp#37]
first is : 

[ip-pool]
gw-ip-address=10.0.0.1
attr=Framed-IP-Address
attr=Framed-Pool
10.50.64.1/18,name=Dynamic Private Pool
172.16.0.1/24,name=Inactive

if after 10.50.64.1/18 ,name=Dynamic Private Pool

have space after network

[   32.228831] accel-ppp[1941]: segfault at 0 ip 0000000000000000 sp 00007ffe03518318 error 14 cpu 2 in accel-ppp[400000+6000]
[   32.267918] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.

service crash brutal 🙂

-------------------------

Second is more brutal not have check if accel-ppp receive broken service-name:
i one of servers service stop without any error

and run in gdb
now run with level=5 log and verbose on pppoe

to see what service name receive
problem is here :       conn->service_name = _malloc(sizeof(*service_name) + ntohs(service_name->tag_len));
        memcpy(conn->service_name, service_name, sizeof(*service_name) + ntohs(service_name->tag_len));
pppoe.c line 349
size of service name
if receive big service name service crash

[debug.txt](https://github.com/dpdk-vbng-cp/accel-ppp/files/8952607/debug.txt)

Martin Zaharinov, [14 Jun 2022, 23:39:34]:
[2022-06-15 02:08:05.357] vlan435: recv [PPPoE PADR 00:17:7c:6c:05:f8 => ac:1f:6b:a4:0b:6a sid=0000 <Unknown (401)> <AC-Cookie 10b3c3fdaeec9713727ed08c789098c3e0cc739b78101c39>]
this is D-link device
this is start session:

[2022-06-15 02:08:03.879] vlan435: recv [PPPoE PADT 00:17:7c:6c:05:f8 => ac:1f:6b:a4:0b:6a sid=a683]
[2022-06-15 02:08:03.993] vlan435: recv [PPPoE PADI 00:17:7c:6c:05:f8 => ff:ff:ff:ff:ff:ff sid=0000 <Service-Name govir> <Host-Uniq 707070326531>]
[2022-06-15 02:08:03.993] vlan435: send [PPPoE PADO ac:1f:6b:a4:0b:6a => 00:17:7c:6c:05:f8 sid=0000 <AC-Name GOVIR> <Service-Name govir> <AC-Cookie 10b3c3fdaeec9713727ed08c789098c3e0cc739b78101c39> <Host-Uniq 707070326531>]

[log.txt](https://github.com/dpdk-vbng-cp/accel-ppp/files/8952608/log.txt)

this is full log for this mac address

i talk with Dimka88 but hi is in Ukrain and not posible to fix this .
Here need to have check if service-name is broken to  rejected query.

for now i block mac address : 

add in pppoe section : mac-filter=/etc/accel/macdeny,deny
and block this mac address

**Comment by akoepsel** [comment]
Regarding the **first** issue you described:

I have to do some more intense investigation of that crash. Will fix that soon.

Regarding the **second** issue you described:

You are right, there should be a sanity check (or two) to handle special cases properly.

Just added two of them to deal with zero length service names as well as to ignore service name tags exceeding (1484-8-4) bytes in length according to RFC 2516. See 
https://github.com/dpdk-vbng-cp/accel-ppp/blob/37-service-name-tag-error/accel-pppd/ctrl/pppoe/pppoe.c#L1194
for details. Hope this fixes this particular problem, please give it a try.

**Comment by micron10** [comment]
fix
